In [5]:
import requests
from datetime import datetime, timedelta
import pandas as pd

# Replace 'YOUR_ACCESS_KEY' with your actual API access key
access_key = 'API KEY Here'

start_date = datetime(2021, 1, 1).date()


# Define the target currencies (ZAR, EUR, USD)
target_currencies = 'ZAR,EUR,USD'

# Construct the URL for the API request

exchange_rate_data = pd.DataFrame(columns=['Date', 'ZAR', 'EUR', 'USD'])

def fetchExchangeRates(date):
    # Send an HTTP GET request to the API
    url = f'http://api.exchangeratesapi.io/v1/{date}?access_key={access_key}&symbols={target_currencies}'
    response = requests.get(url)
    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        data = response.json()
        

        # Extract exchange rates for the target currencies
        zar_rate = data['rates']['ZAR']
        eur_rate = data['rates']['EUR']
        usd_rate = data['rates']['USD']
        exchange_rate_data.loc[len(exchange_rate_data)] = [date, zar_rate, eur_rate, usd_rate]

        # Print the exchange rates
        print(f'Exchange Rates on {date}:')
        print(f'{zar_rate} ZAR')
        print(f'{eur_rate} EUR')
        print(f'{usd_rate} USD')
        return data

In [6]:
start_date = datetime(2023,10,4).date()
current_date = datetime.now().date()  # Adjust the current date to include the end date
while current_date >= start_date:
    formatted_date = start_date.strftime('%Y-%m-%d')
    fetchExchangeRates(formatted_date)
    start_date += timedelta(days=1)

Exchange Rates on 2023-10-04:
20.314151 ZAR
1 EUR
1.050663 USD
Exchange Rates on 2023-10-05:
20.595688 ZAR
1 EUR
1.054618 USD
Exchange Rates on 2023-10-06:
20.481711 ZAR
1 EUR
1.060051 USD
Exchange Rates on 2023-10-07:
20.481711 ZAR
1 EUR
1.060051 USD
Exchange Rates on 2023-10-08:
20.456818 ZAR
1 EUR
1.056631 USD
Exchange Rates on 2023-10-09:
20.354065 ZAR
1 EUR
1.05786 USD
Exchange Rates on 2023-10-10:
20.162034 ZAR
1 EUR
1.06044 USD
Exchange Rates on 2023-10-11:
19.998125 ZAR
1 EUR
1.0624 USD
Exchange Rates on 2023-10-12:
20.04709 ZAR
1 EUR
1.053635 USD
Exchange Rates on 2023-10-13:
19.98559 ZAR
1 EUR
1.051469 USD
Exchange Rates on 2023-10-14:
19.98559 ZAR
1 EUR
1.051469 USD
Exchange Rates on 2023-10-15:
19.964343 ZAR
1 EUR
1.052111 USD
Exchange Rates on 2023-10-16:
19.823463 ZAR
1 EUR
1.055403 USD
Exchange Rates on 2023-10-17:
19.883617 ZAR
1 EUR
1.057139 USD
Exchange Rates on 2023-10-18:
20.000722 ZAR
1 EUR
1.053824 USD
Exchange Rates on 2023-10-19:
20.120002 ZAR
1 EUR
1.058257 USD

In [7]:
csv_filename = 'exchange_rates1.csv'
exchange_rate_data.to_csv(csv_filename, index=False)

In [20]:
exchange_rate_data.tail()

           Date        ZAR  EUR       USD
974  2021-02-02  18.004767    1  1.203869
975  2021-02-01  18.176897    1  1.206833
976  2021-01-31  18.413054    1  1.212341
977  2021-01-30  18.421574    1  1.213750
978  2021-01-29  18.408769    1  1.213770